# Generated by Django 5.1 on 2024-09-25 14:50

import django.core.validators
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'tiff', 'txt', 'doc', 'docx', 'pdf', 'xls', 'xlsx'])], verbose_name='Файл')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('file_path', models.CharField(blank=True, default='', max_length=255, verbose_name='Путь к файлу в хранилище')),
                ('special_link', models.CharField(blank=True, default='', max_length=255, verbose_name='Специальная ссылка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['user', '-uploaded_at'],
            },
        ),
    ]
